import argparse, os

def add_arguments(parser):

    parser.add_argument("--server", dest="server", help="xrootd server",default=os.environ["EOSSHIP"])
    parser.add_argument("-r", "--runNumber", dest="runNumber", help="run number", type=int,default=-1)
    parser.add_argument('-p', '--path', dest='path', help='path', default='./', type=str)
    # parser.add_argument("-P", "--partition", dest="partition", help="partition of data", type=int,required=False,default=-1)
    parser.add_argument("-d", "--debug", dest="debug", help="debug", type=int, default=False)
    parser.add_argument("-cpp", "--convRawCPP", action='store_true', dest="FairTask_convRaw", help="convert raw data using ConvRawData FairTask", default=False)
    parser.add_argument( "--withCalibration", action='store_true', dest="makeCalibration", help="make QDC and TDC calibration, not taking from raw data", default=False)
    parser.add_argument("--customEventChain", dest="customEventChain", action="store_true")

    parser.add_argument("-f", "--inputFile", dest="fname", help="file name for MC", type=str,default=None,required=False)
    parser.add_argument("-g", "--geoFile", dest="geoFile", help="geofile", required=False,default=False)
    parser.add_argument("-c", "--command", dest="command", help="command", default="")
    parser.add_argument("-n", "--nEvents", dest="nEvents", help="number of events", default=500000, type=int)
    parser.add_argument("-s", "--nStart", dest="nStart", help="first event", default=0,type=int)
    parser.add_argument("-t", "--trackType", dest="trackType", help="DS or Scifi", default="DS")
    parser.add_argument("--CorrectionType", dest="CorrectionType", help="Type of polynomial function or log function", default=5, type=int, required=False)
    parser.add_argument("--Task", dest="Task", help="TimeWalk or SelectionCriteria", default="TimeWalk")
    parser.add_argument("--TWCorrectionRun", dest="TWCorrectionRun", help="Select what run to take TW correction parameters from. By default it is the same as the data", type=str, default='005408')
    parser.add_argument('-D', '--datalocation', dest='datalocation', type=str, default='physics')
    parser.add_argument('--state', dest='state', type=str, default='uncorrected')
    parser.add_argument('--referencesystem', dest='referencesystem', type=int, default=3)

    # Cuts
    parser.add_argument('--OneHitPerSystem', dest='OneHitPerSystem', action='store_true')
    parser.add_argument('--SlopesCut', dest='SlopesCut', action='store_true')
    parser.add_argument('--XT', dest='XT', action='store_true')

    parser.add_argument('--afswork', dest='afswork', type=str, default='/afs/cern.ch/work/a/aconsnd/Timing')
    parser.add_argument('--afsuser', dest='afsuser', type=str, default='/afs/cern.ch/user/a/aconsnd/Timing')
    parser.add_argument('--eosH8', dest='eosH8', type=str, default='/eos/experiment/sndlhc/convertedData/commissioning/TB_H8_october/')
    parser.add_argument('--eosTI18', dest='eosTI18', type=str, default='/eos/experiment/sndlhc/convertedData/commissioning/TI18/')
    parser.add_argument('--mode', dest='mode', type=str, default='zeroth')
    parser.add_argument('-C', '--HTCondor', dest='HTCondor', action='store_true')
    parser.add_argument('--numusignalevents', dest='numusignalevents', action='store_true')
    parser.add_argument('--signalpartitions', dest='signalpartitions', required=False)
    parser.add_argument('--numuStudy', dest='numuStudy', action='store_true')
    parser.add_argument('--nueStudy', dest='nueStudy', action='store_true')
    parser.add_argument('--simulation', dest='simulation', action='store_true')
    parser.add_argument('--simMode', dest='simMode', type=str)
    parser.add_argument('--simTest', dest='simTest', action='store_true')
    parser.add_argument('--OutgoingMuon', dest='OutgoingMuon', type=str, default='all')
    parser.add_argument('--allFiles', dest='allFiles', action='store_true')

    parser.add_argument('-S', '--subsystem', dest='subsystem', help='fixed subsystem', type=int, default=2)    
    parser.add_argument('-P', '--Plane', dest='Plane', help='fixed plane', type=int, default=0)
    parser.add_argument('-B', '--Bar', dest='Bar', help='fixed bar', type=int, default=0)

    parser.add_argument("--WriteOutTrackInfo", dest="WriteOutTrackInfo", type=int, default=0)
    parser.add_argument('--numbering', dest='numbering', type=str, default='systemPCB')
    parser.add_argument('--gel', dest='gel', type=int, default=0, help='Set as 1 to distinguish between SiPMs w/ gel. Only for US. Default is False', required=False)
    parser.add_argument('--systematics', dest='systematics', action='store_true')